# Generated by Django 5.2.11 on 2026-05-31 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='Код')),
                ('price_monthly', models.PositiveIntegerField(default=0, verbose_name='Цена в месяц, ₽')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('max_projects', models.PositiveIntegerField(default=1, verbose_name='Макс. проектов')),
                ('audit_frequency', models.CharField(choices=[('manual', 'Вручную'), ('weekly', 'Раз в неделю'), ('daily', 'Ежедневно')], default='manual', max_length=10, verbose_name='Частота автоаудита')),
                ('ai_limit', models.PositiveIntegerField(default=0, verbose_name='AI-рекомендаций в месяц')),
                ('max_integrations', models.PositiveIntegerField(blank=True, help_text='Пусто = без лимита', null=True, verbose_name='Макс. интеграций')),
                ('history_days', models.PositiveIntegerField(blank=True, help_text='Пусто = без лимита', null=True, verbose_name='История, дней')),
                ('telegram_alerts', models.BooleanField(default=False, verbose_name='Telegram-алерты')),
            ],
            options={
                'verbose_name': 'Тариф',
                'verbose_name_plural': 'Тарифы',
                'ordering': ['sort_order'],
            },
        ),
    ]
