# Generated by Django 5.2.11 on 2026-05-31 06:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('trial', 'Триал'), ('active', 'Активна'), ('past_due', 'Просрочена'), ('canceled', 'Отменена')], default='active', max_length=10, verbose_name='Статус')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Начало')),
                ('expires_at', models.DateTimeField(blank=True, help_text='Пусто = бессрочно (например, Free)', null=True, verbose_name='Истекает')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='billing.plan', verbose_name='Тариф')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Подписка',
                'verbose_name_plural': 'Подписки',
            },
        ),
    ]
