# Generated by Django 6.0 on 2025-12-18 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_up', models.BooleanField(default=False)),
                ('http_status', models.IntegerField(blank=True, null=True)),
                ('error', models.TextField(blank=True, default='')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checks', to='core.site')),
            ],
        ),
    ]
