# Generated by Django 6.0 on 2026-02-01 10:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_checkrun_options_remove_checkrun_error_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yandex_connected', models.BooleanField(default=False, verbose_name='Яндекс подключен')),
                ('telegram_enabled', models.BooleanField(default=False, verbose_name='Уведомления в Telegram включены')),
                ('telegram_chat_id', models.CharField(blank=True, default='', max_length=64, verbose_name='Telegram chat_id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
