# Generated by Django 6.0 on 2026-02-01 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='telegram_enabled',
            field=models.BooleanField(default=False, verbose_name='Telegram-уведомления включены'),
        ),
    ]
