# Generated by Django 6.0 on 2026-02-04 12:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_userprofile_telegram_enabled'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='YandexOAuthToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField(blank=True, default='')),
                ('token_type', models.CharField(blank=True, default='', max_length=32)),
                ('scope', models.CharField(blank=True, default='', max_length=255)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('last_refresh_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='yandex_token', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='YandexSiteConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_id', models.CharField(blank=True, default='', max_length=128)),
                ('host_url', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('not_connected', 'Не подключено'), ('connected_ok', 'Подключено'), ('connected_no_hosts', 'Нет хостов'), ('auth_expired', 'Доступ истёк'), ('api_error', 'Ошибка API'), ('data_not_ready', 'Данных нет')], default='not_connected', max_length=32)),
                ('last_error_code', models.CharField(blank=True, default='', max_length=64)),
                ('last_error_message', models.TextField(blank=True, default='')),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('connected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='yandex_connections', to=settings.AUTH_USER_MODEL)),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='yandex_connection', to='core.site')),
                ('token', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_connections', to='core.yandexoauthtoken')),
            ],
        ),
    ]
