# Generated by Django 6.0 on 2026-02-08 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_yandexoauthtoken_yandexsiteconnection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yandexsiteconnection',
            name='token',
        ),
        migrations.RemoveField(
            model_name='yandexsiteconnection',
            name='connected_by',
        ),
        migrations.RemoveField(
            model_name='yandexsiteconnection',
            name='site',
        ),
        migrations.AddField(
            model_name='site',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Удалён'),
        ),
        migrations.AddField(
            model_name='site',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Удалён'),
        ),
        migrations.DeleteModel(
            name='YandexOAuthToken',
        ),
        migrations.DeleteModel(
            name='YandexSiteConnection',
        ),
    ]
