# Generated by Django 6.0 on 2026-02-22 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_yandexsiteconnection_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='manual_indexed_pages',
            field=models.IntegerField(blank=True, null=True, verbose_name='Страниц в индексе (ручной)'),
        ),
        migrations.AddField(
            model_name='site',
            name='manual_traffic_week',
            field=models.IntegerField(blank=True, null=True, verbose_name='Трафик за неделю (ручной)'),
        ),
    ]
