# Generated by Django 5.2.11 on 2026-02-28 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_yandexoauth'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='yandex_metrica_counter_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
