# Generated by Django 5.2.11 on 2026-02-28 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_site_yandex_metrica_counter_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='yandex_webmaster_host_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
