# Generated by Django 5.2.11 on 2026-02-28 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_site_yandex_webmaster_host_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='yandexoauth',
            name='webmaster_user_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
