# Generated by Django 5.2.11 on 2026-03-17 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_yandexoauth_webmaster_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint', models.CharField(db_index=True, max_length=128)),
                ('check_key', models.CharField(db_index=True, max_length=64)),
                ('severity', models.CharField(choices=[('fail', 'Fail'), ('warn', 'Warn')], max_length=8)),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved'), ('muted', 'Muted')], default='open', max_length=16)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('last_checkrun', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues_seen', to='core.checkrun')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='core.site')),
            ],
            options={
                'unique_together': {('site', 'fingerprint')},
            },
        ),
    ]
