# Generated by Django 5.2.11 on 2026-04-04 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_issue'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueSolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_key', models.CharField(help_text='Ключ проверки, например: http, ssl, domain, dns, metrics', max_length=100)),
                ('issue_code', models.CharField(blank=True, default='', help_text='Опциональный код/подтип проблемы, например: http_403, ssl_expiring, traffic_drop', max_length=150)),
                ('severity', models.CharField(choices=[('warn', 'Warning'), ('fail', 'Fail')], help_text='Для какого уровня проблемы подходит решение', max_length=10)),
                ('title', models.CharField(help_text='Название решения', max_length=255)),
                ('short_summary', models.TextField(blank=True, default='', help_text='Короткое описание, что произошло и что обычно делать')),
                ('steps', models.JSONField(blank=True, default=list, help_text="Список шагов решения, например: ['Проверить X', 'Сделать Y']")),
                ('links', models.JSONField(blank=True, default=list, help_text="Список ссылок, например: [{'label': 'Документация', 'url': 'https://...'}]")),
                ('match_rules', models.JSONField(blank=True, default=dict, help_text="Доп. условия для матчинга. Например: {'http_status': 403} или {'metric_name': 'sqi'}")),
                ('priority', models.PositiveIntegerField(default=100, help_text='Чем меньше число, тем выше приоритет')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['priority', 'id'],
                'indexes': [models.Index(fields=['check_key', 'severity', 'is_active'], name='core_issues_check_k_395439_idx'), models.Index(fields=['issue_code', 'severity', 'is_active'], name='core_issues_issue_c_e64142_idx')],
            },
        ),
    ]
