# Generated by Django 6.0.3 on 2026-04-24 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_issuesolution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='domain',
            field=models.CharField(max_length=255, verbose_name='Домен'),
        ),
    ]
