# Generated by Django 6.0.3 on 2026-04-30 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_site_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='onboarding_done',
            field=models.BooleanField(default=False, verbose_name='Онбординг пройден'),
        ),
    ]
