# Generated by Django 6.0.3 on 2026-07-23 14:59

import core.crypto
from django.db import migrations


def encrypt_existing_tokens(apps, schema_editor):
    """
    Шифрует токены, записанные до перехода на EncryptedTextField.

    Ходим в обход ORM-поля: историческая модель уже знает про шифрование,
    и обычный .save() зашифровал бы значение, которое from_db_value отдал
    как есть. Читаем и пишем сырые строки курсором.
    """
    from cryptography.fernet import InvalidToken

    from core.crypto import decrypt, encrypt

    table = apps.get_model("core", "YandexOAuth")._meta.db_table
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(f"SELECT id, access_token, refresh_token FROM {table}")
        rows = cursor.fetchall()

        for pk, access, refresh in rows:
            updates = {}
            for column, value in (("access_token", access), ("refresh_token", refresh)):
                if not value:
                    continue
                try:
                    decrypt(value)
                except InvalidToken:
                    updates[column] = encrypt(value)  # была открытая строка
            for column, value in updates.items():
                cursor.execute(
                    f"UPDATE {table} SET {column} = %s WHERE id = %s", [value, pk]
                )


def decrypt_existing_tokens(apps, schema_editor):
    """Обратная миграция: возвращаем открытый текст, иначе откат ломает доступ."""
    from cryptography.fernet import InvalidToken

    from core.crypto import decrypt

    table = apps.get_model("core", "YandexOAuth")._meta.db_table
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(f"SELECT id, access_token, refresh_token FROM {table}")
        rows = cursor.fetchall()

        for pk, access, refresh in rows:
            for column, value in (("access_token", access), ("refresh_token", refresh)):
                if not value:
                    continue
                try:
                    plain = decrypt(value)
                except InvalidToken:
                    continue  # уже открытая строка
                cursor.execute(
                    f"UPDATE {table} SET {column} = %s WHERE id = %s", [plain, pk]
                )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_aiusage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yandexoauth',
            name='access_token',
            field=core.crypto.EncryptedTextField(),
        ),
        migrations.AlterField(
            model_name='yandexoauth',
            name='refresh_token',
            field=core.crypto.EncryptedTextField(blank=True, null=True),
        ),
        migrations.RunPython(encrypt_existing_tokens, decrypt_existing_tokens),
    ]
