# Generated by Django 5.2.11 on 2026-06-13 15:10

import landing.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeoLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=2000, verbose_name='Проверяемый URL')),
                ('channel', models.CharField(choices=[('email', 'Email'), ('telegram', 'Telegram')], max_length=16, verbose_name='Канал доставки')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Email')),
                ('tg_token', models.CharField(db_index=True, default=landing.models._gen_tg_token, max_length=64, unique=True, verbose_name='TG-токен')),
                ('tg_chat_id', models.CharField(blank=True, default='', max_length=64, verbose_name='TG chat_id')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('done', 'Отправлено')], default='pending', max_length=16, verbose_name='Статус')),
                ('result_json', models.JSONField(blank=True, default=list, verbose_name='Результат проверки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Отправлено')),
            ],
            options={
                'verbose_name': 'GEO-заявка',
                'verbose_name_plural': 'GEO-заявки',
                'ordering': ['-created_at'],
            },
        ),
    ]
