# Generated by Django 6.0.3 on 2026-06-14 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='geolead',
            name='access_token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='Токен доступа к отчёту'),
        ),
        migrations.AddField(
            model_name='geolead',
            name='ai_report',
            field=models.JSONField(blank=True, default=dict, verbose_name='AI-разбор (кеш)'),
        ),
        migrations.AddField(
            model_name='geolead',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Оплачено'),
        ),
        migrations.AddField(
            model_name='geolead',
            name='pay_status',
            field=models.CharField(choices=[('none', 'Не оплачено'), ('pending', 'Ожидает оплаты'), ('paid', 'Оплачено')], default='none', max_length=16, verbose_name='Статус оплаты'),
        ),
        migrations.AddField(
            model_name='geolead',
            name='recheck_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Перепроверок сделано'),
        ),
        migrations.AddField(
            model_name='geolead',
            name='yk_payment_id',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='YuKassa payment_id'),
        ),
    ]
