# Generated by Django 6.0.3 on 2026-06-15 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_geolead_access_token_geolead_ai_report_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(help_text='Технический идентификатор, напр. geo_report. Не менять без необходимости.', unique=True, verbose_name='Код услуги')),
                ('title', models.CharField(max_length=120, verbose_name='Название')),
                ('price', models.PositiveIntegerField(verbose_name='Цена, ₽')),
                ('old_price', models.PositiveIntegerField(blank=True, help_text='Для отображения скидки. Оставьте пустым, если скидки нет.', null=True, verbose_name='Старая цена, ₽ (зачёркнутая)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Цена услуги',
                'verbose_name_plural': 'Цены услуг',
            },
        ),
    ]
