# Generated by Django 6.0.3 on 2026-06-17 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_serviceprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('slug', models.SlugField(help_text='Латиницей, напр. geo-audit-dlya-magazina. Менять после публикации нежелательно.', max_length=200, unique=True, verbose_name='URL (slug)')),
                ('description', models.CharField(blank=True, default='', help_text='Короткий анонс, попадает в <meta description> и в список статей.', max_length=300, verbose_name='Описание (для SEO и списка)')),
                ('body', models.TextField(verbose_name='Текст статьи')),
                ('cover', models.ImageField(blank=True, help_text='Необязательно. Картинка для шапки статьи.', null=True, upload_to='blog/covers/', verbose_name='Обложка')),
                ('is_published', models.BooleanField(default=False, help_text='Снимите галку, чтобы скрыть статью с сайта (черновик).', verbose_name='Опубликовано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('published_at', models.DateField(blank=True, help_text='Показывается в статье и используется в sitemap. Можно задать вручную.', null=True, verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Статья блога',
                'verbose_name_plural': 'Статьи блога',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
    ]
