# Generated by Django 6.0.3 on 2026-06-17 18:30

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0004_blogpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='body',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Текст статьи'),
        ),
    ]
