# Generated by Django 6.0.3 on 2026-06-17 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0005_alter_blogpost_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='read_time',
            field=models.PositiveIntegerField(default=1, help_text='Считается автоматически при сохранении.', verbose_name='Время чтения, мин'),
        ),
    ]
