# Generated by Django 6.0.3 on 2026-07-02 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0007_faqitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='geolead',
            name='demo_item',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
