# Generated by Django 6.0.3 on 2026-07-07 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_module_question_alter_lesson_options_lesson_is_free_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='video_url',
            field=models.URLField(blank=True, help_text='VK Видео (обычная ссылка или код плеера video_ext.php) либо YouTube', verbose_name='Ссылка на видео'),
        ),
    ]
