# Generated by Django 6.0.3 on 2026-07-09 18:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_alter_lesson_video_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseAccessRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_handled', models.BooleanField(default=False, help_text='Сняли, когда выдали доступ или связались', verbose_name='Обработана')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
                ('lesson', models.ForeignKey(blank=True, help_text='С какого закрытого урока пришла заявка', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_requests', to='course.lesson', verbose_name='Урок-триггер')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_access_requests', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заявка на доступ к курсу',
                'verbose_name_plural': 'Заявки на доступ к курсу',
                'ordering': ['-created_at'],
            },
        ),
    ]
