from django.urls import path
from . import views
from . import course_views

urlpatterns = [
    path("", views.dashboard, name="dashboard"),
    path("register/", views.register, name="register"),
    path("sites/new/", views.site_new, name="site_new"),
    path("integrations/yandex/connect/", views.yandex_connect, name="yandex_connect"),
    path("integrations/yandex/callback/", views.yandex_callback, name="yandex_callback"),
    path("integrations/yandex/disconnect/", views.yandex_disconnect, name="yandex_disconnect"),
    path("sites/<int:site_id>/", views.site_checks, name="site_checks"),
    path("sites/<int:site_id>/edit/", views.site_edit, name="site_edit"),
    path("sites/<int:site_id>/run/", views.run_check, name="run_check"),
    path("sites/<int:site_id>/delete/", views.delete_site, name="delete_site"),
    path("checks/<int:check_id>/", views.check_detail, name="check_detail"),
    path("checks/<int:check_id>/recommendations/", views.ai_recommendations, name="ai_recommendations"),
    path("sites/<int:site_id>/recommendations/", views.site_ai_recommendations, name="site_ai_recommendations"),
    path("alerts/", views.alerts, name="alerts"),
    path("alerts/<int:check_id>/", views.alert_detail, name="alert_detail"),
    path("billing/", views.billing, name="billing"),
    path("billing/pay/<int:plan_id>/", views.create_payment, name="create_payment"),
    path("billing/webhook/", views.yookassa_webhook, name="yookassa_webhook"),
    path("team/", views.team, name="team"),
    path("help/", views.help_page, name="help"),
    path("account/settings/", views.user_settings, name="user_settings"),
    path("account/password/", views.account_change_password, name="account_change_password"),
    path("account/email/", views.account_change_email, name="account_change_email"),
    path("account/export/", views.account_export, name="account_export"),
    path("account/delete/", views.account_delete, name="account_delete"),
    path("issues/<int:issue_id>/mute/", views.issue_mute, name="issue_mute"),
    path("issues/<int:issue_id>/resolve/", views.issue_resolve, name="issue_resolve"),
    path("sites/<int:site_id>/rename/", views.site_rename, name="site_rename"),
    path("telegram/webhook/", views.telegram_webhook, name="telegram_webhook"),
    path("onboarding/done/", views.onboarding_done, name="onboarding_done"),
    path("sites/new/integrations/", views.site_new_integrations, name="site_new_integrations"),
    path("analytics/", views.analytics, name="analytics"),
    path("course/", course_views.course_index, name="course_index"),
    path("course/<slug:slug>/", course_views.course_lesson, name="course_lesson"),
]
