# Generated by Django 6.0.3 on 2026-05-21 19:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0018_aiusage'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('running', 'Выполняется'), ('done', 'Завершён'), ('error', 'Ошибка')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('results', models.JSONField(default=dict)),
                ('summary', models.TextField(blank=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audits', to='core.site')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
