# Generated by Django 6.0.3 on 2026-05-28 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditresult',
            name='block_summaries',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
