"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Важно: сначала грузим .env из корня проекта
load_dotenv(BASE_DIR / ".env")

TELEGRAM_BOT_TOKEN = os.getenv("TELEGRAM_BOT_TOKEN")
# Секрет вебхука Telegram: тот же, что передан в setWebhook(secret_token=...).
# Telegram присылает его в заголовке X-Telegram-Bot-Api-Secret-Token —
# без этой проверки эндпоинт принимает поддельные апдейты от кого угодно.
TELEGRAM_WEBHOOK_SECRET = os.getenv("TELEGRAM_WEBHOOK_SECRET", "")
# Ключ Fernet для шифрования OAuth-токенов в базе (см. core.crypto).
# Сгенерировать: python -c "from cryptography.fernet import Fernet;
#                           print(Fernet.generate_key().decode())"
# Потеря ключа = потеря токенов: пользователям придётся переподключить Яндекс.
CREDENTIALS_ENCRYPTION_KEY = os.getenv("CREDENTIALS_ENCRYPTION_KEY", "")
WHOISXML_API_KEY = os.getenv("WHOISXML_API_KEY", "")
YANDEX_CLIENT_ID = os.getenv("YANDEX_CLIENT_ID", "")
YANDEX_CLIENT_SECRET = os.getenv("YANDEX_CLIENT_SECRET", "")
YANDEX_REDIRECT_URI = os.getenv("YANDEX_REDIRECT_URI", "")
YANDEX_SCOPE = os.getenv("YANDEX_SCOPE", "metrika:read webmaster:verify")
YOOKASSA_SHOP_ID = os.getenv("YOOKASSA_SHOP_ID", "")
YOOKASSA_SECRET_KEY = os.getenv("YOOKASSA_SECRET_KEY", "")

APP_DOMAIN = "app.seodyssey.ru"




# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# Ключ подписывает сессии, CSRF-токены и ссылки сброса пароля — держим его
# только в .env. Дефолта нет намеренно: без переменной прод должен падать
# на старте, а не молча работать с предсказуемым ключом.
SECRET_KEY = os.environ["DJANGO_SECRET_KEY"]

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = [
    "79.174.86.23",
    "127.0.0.1",
    "localhost",
    "seodyssey.ru",
    "www.seodyssey.ru",
    "app.seodyssey.ru",
    "147.45.171.100",
]

CSRF_TRUSTED_ORIGINS = [
    "https://seodyssey.ru",
    "https://www.seodyssey.ru",
]

SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
CSRF_COOKIE_SECURE = True
SESSION_COOKIE_SECURE = True

# --- Заголовки безопасности ---
# HSTS: браузер сам переключается на https и не даёт кликнуть «продолжить»
# при подменённом сертификате. Год + поддомены — значения для preload-списка.
# Включать, только когда https работает на всех поддоменах: откатить нельзя,
# браузеры помнят заголовок весь срок.
SECURE_HSTS_SECONDS = 31536000
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True
# Дублирует редирект nginx — страховка на случай, если конфиг переедет.
SECURE_SSL_REDIRECT = True
# Не отдавать полный URL кабинета сторонним сайтам: в путях есть id сайтов
# и токены отчётов.
SECURE_REFERRER_POLICY = "strict-origin-when-cross-origin"
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = "DENY"

SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = "Lax"
CSRF_COOKIE_SAMESITE = "Lax"
SESSION_COOKIE_AGE = 60 * 60 * 24 * 14  # две недели

# Локальная разработка: экспортировать SEODYSSEY_DEV=1 перед runserver.
# На сервере переменная не задана — блок не выполняется.
if os.getenv("SEODYSSEY_DEV") == "1":
    DEBUG = True
    CSRF_COOKIE_SECURE = False
    SESSION_COOKIE_SECURE = False
    # Локально всё по http, иначе runserver уйдёт в бесконечный редирект
    # и запишет HSTS в браузер на год — потом на localhost не зайти.
    SECURE_SSL_REDIRECT = False
    SECURE_HSTS_SECONDS = 0
    SECURE_HSTS_PRELOAD = False
    ALLOWED_HOSTS += ["seodyssey.localhost", "app.seodyssey.localhost"]
    CSRF_TRUSTED_ORIGINS += [
        "http://localhost:8642",
        "http://127.0.0.1:8642",
        "http://seodyssey.localhost:8642",
        "http://app.seodyssey.localhost:8642",
    ]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'landing',
    'django.contrib.staticfiles',
    'core.apps.CoreConfig',
    'ai_queries',
    'audits',
    'billing',
    'course',
    'notifications',
    'django_ckeditor_5',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'core.middleware.AppDomainMiddleware',
    'core.middleware.ActivityMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'course.context_processors.course_nav',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

# Счётчик неудачных попыток входа. Стоит вместо стандартного ModelBackend,
# чтобы прикрыть сразу все точки входа — и форму кабинета, и админку.
AUTHENTICATION_BACKENDS = ["core.login_throttle.ThrottledModelBackend"]

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'ru'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / "staticfiles"
# Корневая папка static/ — источник для collectstatic и локального runserver
STATICFILES_DIRS = [BASE_DIR / "static"]
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"
LOGIN_URL = "/login/"
LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/login/"


CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379/1",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        },
        "TIMEOUT": 3600,  # 1 час
    }
}

# Celery
CELERY_BROKER_URL = "redis://127.0.0.1:6379/0"
CELERY_RESULT_BACKEND = "redis://127.0.0.1:6379/0"
CELERY_TASK_SERIALIZER = "json"
CELERY_ACCEPT_CONTENT = ["json"]

# --- Логи ---
# Пишем в stdout/stderr: gunicorn и celery запущены под systemd, он всё
# складывает в journald (`journalctl -u seodyssey`). Файловых хендлеров
# намеренно нет — не нужны ни права на каталог, ни своя ротация.
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "standard": {
            "format": "{asctime} {levelname} {name}: {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "standard",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "WARNING",
    },
    "loggers": {
        # Наш код — на INFO, чтобы было видно отказы вебхука и списания лимитов.
        "core": {"level": "INFO"},
        "landing": {"level": "INFO"},
        "audits": {"level": "INFO"},
        "ai_queries": {"level": "INFO"},
        "billing": {"level": "INFO"},
        "notifications": {"level": "INFO"},
        "django.request": {"level": "ERROR"},
    },
}

# --- CKEditor 5 ---
CKEDITOR_5_FILE_STORAGE = "django.core.files.storage.FileSystemStorage"
# svg убран намеренно: файл исполняет JS при открытии по прямой ссылке,
# а media/ отдаётся с нашего домена — это был бы XSS на seodyssey.ru.
CKEDITOR_5_UPLOAD_FILE_TYPES = ["jpg", "jpeg", "png", "gif", "webp"]

CKEDITOR_5_CONFIGS = {
    "default": {
        "toolbar": [
            "heading", "|",
            "bold", "italic", "link", "|",
            "bulletedList", "numberedList", "blockQuote", "|",
            "imageUpload", "insertTable", "|",
            "undo", "redo",
        ],
        "image": {
            "toolbar": [
                "imageTextAlternative", "|",
                "imageStyle:alignLeft", "imageStyle:alignCenter", "imageStyle:alignRight",
            ],
        },
        "table": {
            "contentToolbar": ["tableColumn", "tableRow", "mergeTableCells"],
        },
    },
}

# === Email (Timeweb SMTP) ===
# SMTP-порты наружу заблокированы на VPS Timeweb — шлём через HTTPS API Unisender Go
EMAIL_BACKEND = "notifications.backends.UnisenderGoBackend"
EMAIL_HOST = "smtp.go2.unisender.ru"
EMAIL_PORT = 587
EMAIL_USE_SSL = False
EMAIL_USE_TLS = True
EMAIL_HOST_USER = "8255186"
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "")
DEFAULT_FROM_EMAIL = "SEOdyssey <info@seodyssey.ru>"
SERVER_EMAIL = "info@seodyssey.ru"
EMAIL_TIMEOUT = 20

# Транзакционные письма (notifications)
UNISENDER_GO_API_KEY = os.getenv("EMAIL_HOST_PASSWORD", "")  # API-ключ = SMTP-пароль Go
# Включить после того, как поддержка Go включит аккаунту allow_skip_unsubscribe
UNISENDER_GO_SKIP_UNSUBSCRIBE = False
SITE_URL = "https://seodyssey.ru"  # абсолютные ссылки в письмах
OWNER_NOTIFICATION_EMAIL = "info@seodyssey.ru"  # уведомления владельцу сервиса
EMAIL_ASYNC = True  # слать через Celery; False — синхронно (тесты, dev без Redis)
# Message-ID должен использовать FQDN домена, а не хостнейм сервера ("seodyssey").
# Иначе Gmail может молча отбрасывать письма.
from django.core.mail import utils as _mail_utils
_mail_utils.DNS_NAME._fqdn = "seodyssey.ru"