# Generated by Django 6.0.3 on 2026-05-14 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_queries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordstatCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase', models.CharField(max_length=512, unique=True)),
                ('count', models.IntegerField(null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Wordstat cache',
            },
        ),
    ]
