# Generated by Django 6.0.3 on 2026-05-16 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_queries', '0002_wordstatcache'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiqueryresult',
            name='query_types',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
