# Generated by Django 6.0.3 on 2026-05-20 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_queries', '0003_aiqueryresult_query_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiqueryresult',
            name='visibility',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
