# Generated by Django 6.0.3 on 2026-05-22 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_queries', '0005_geoauditresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='geoauditresult',
            name='progress',
            field=models.IntegerField(default=0),
        ),
    ]
