# Generated by Django 6.0.3 on 2026-07-20 22:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0018_aiusage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('welcome', 'Приветствие после регистрации'), ('owner_registration', 'Владельцу: новая регистрация'), ('owner_payment', 'Владельцу: успешная оплата'), ('ssl_expiry', 'SSL истекает'), ('domain_expiry', 'Домен истекает')], max_length=32, verbose_name='Событие')),
                ('to_email', models.EmailField(max_length=254, verbose_name='Кому')),
                ('subject', models.CharField(max_length=255, verbose_name='Тема')),
                ('threshold_days', models.IntegerField(blank=True, null=True, verbose_name='Порог, дней')),
                ('expires_on', models.DateField(blank=True, null=True, verbose_name='Истекает')),
                ('status', models.CharField(choices=[('queued', 'В очереди'), ('sent', 'Отправлено'), ('failed', 'Ошибка')], default='queued', max_length=12, verbose_name='Статус')),
                ('error', models.TextField(blank=True, default='', verbose_name='Ошибка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Отправлено')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_logs', to='core.site', verbose_name='Сайт')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_logs', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Письмо',
                'verbose_name_plural': 'Журнал писем',
                'indexes': [models.Index(fields=['site', 'event', 'threshold_days'], name='notificatio_site_id_199073_idx')],
            },
        ),
    ]
